services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/workspace/kishimen/frontend
    stdin_open: true
    tty: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/workspace/kishimen/backend
    expose:
      - "8000"
    stdin_open: true
    tty: true
